# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-16 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaskingRidgeFiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_entry',
            name='menu_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Social Events', 'Social Events'), ('Sweet Sixteens', 'Sweet Sixteens'), ('Corporate', 'Sweet Sixteens')], default='Weddings', max_length=120),
        ),
    ]
