# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-06 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaskingRidgeFiles', '0002_menu_entry_menu_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_entry',
            name='description',
        ),
        migrations.AddField(
            model_name='menu_entry',
            name='menu_order',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='menu_entry',
            name='menu_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Social Events', 'Social Events'), ('Sweet Sixteens', 'Sweet Sixteens'), ('Corporate', 'Corporate')], default='Weddings', max_length=120),
        ),
    ]
