# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-09 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaskingRidgeFiles', '0003_auto_20171205_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu_entry',
            options={'ordering': ['my_order'], 'verbose_name': 'Menu Entry', 'verbose_name_plural': 'Menu Entries'},
        ),
        migrations.AddField(
            model_name='menu_entry',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
