# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-04 17:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('TwinBrooksUser', '0002_auto_20170107_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, help_text='Required. 255 characters or fewer. Letters, numbers and             @/./+/-/_ characters', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'Enter a valid username.', 'invalid')], verbose_name='Username'),
        ),
    ]
