# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-11 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TwinBrooksUser', '0004_auto_20170411_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'WVGC Site User', 'verbose_name_plural': 'WVGC Site Users'},
        ),
    ]
