# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-12 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwinBrooksUser', '0005_auto_20170411_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_level',
            field=models.CharField(blank=True, choices=[('full_membership', 'Full Membership'), ('weekday_membership', 'Weekday Membership'), ('social_membership', 'Social Membership'), ('young_executive_membership', 'Young Executive Membership'), ('senior_membership', 'Senior Membership'), ('national_membership', 'National Membership')], max_length=120, verbose_name='Membership Level'),
        ),
    ]
