# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-12 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwinBrooksUser', '0007_user_member_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_level',
            field=models.CharField(blank=True, max_length=120, verbose_name='Membership Level'),
        ),
    ]
