# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-25 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwinBrooksUser', '0008_auto_20170512_1001'),
    ]

    operations = [

    ]
