# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-25 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwinBrooksUser', '0009_auto_20170525_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member_code',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Member Code'),
        ),
    ]
