# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-25 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwinBrooksUser', '0010_auto_20170525_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_numner', models.CharField(blank=True, max_length=60, verbose_name='Phone Number')),
                ('member_code', models.CharField(blank=True, max_length=60, verbose_name='Member Code')),
            ],
        ),
    ]
