# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-29 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwinBrooksUser', '0011_userphonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='needs_to_be_put_into_event_man',
            field=models.BooleanField(default=False),
        ),
    ]
